"""Initial migration

Revision ID: faa2040df14b
Revises: 
Create Date: 2025-09-13 20:19:05.902840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa2040df14b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Numeric(precision=16, scale=0), nullable=True),
    sa.Column('holder_name', sa.String(length=45), nullable=True),
    sa.Column('holder_identifier', sa.String(length=45), nullable=True),
    sa.Column('agency', sa.String(length=45), nullable=True),
    sa.Column('operation', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('icon', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('identifier', sa.String(length=45), nullable=True),
    sa.Column('document_path', sa.String(length=45), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BIKE', 'MOTORCYCLE', 'CAR'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('banking_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banking_info_id'], ['banking_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['products_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('banking_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banking_info_id'], ['banking_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.String(length=45), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('security_code', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=45), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_method', sa.Enum('CARTAO', 'PIX'), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'ON GOING', 'DRAFT'), nullable=True),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=True),
    sa.Column('brand', sa.String(length=45), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('care_level', sa.Enum('BAIXO', 'MEDIO', 'ALTO'), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_product_id', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['seller_product_id'], ['seller_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_product_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_product_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.Enum('VERMELHO', 'BRANCO', 'AMARELO', 'LARANJA', 'VERDE', 'AZUL', 'CINZA', 'ROSA', 'ROXO', 'BEGE'), nullable=True),
    sa.Column('size', sa.Enum('PP', 'P', 'M', 'G', 'GG', 'XG', 'XG1', 'XG2', 'XG3'), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_product_id'], ['seller_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_product_details')
    op.drop_table('order_product')
    op.drop_table('seller_product')
    op.drop_table('order')
    op.drop_table('card_info')
    op.drop_table('seller')
    op.drop_table('product')
    op.drop_table('driver')
    op.drop_table('client')
    op.drop_table('user')
    op.drop_table('products_category')
    op.drop_table('banking_info')
    # ### end Alembic commands ###
